apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config/config.yaml
  - postgres/postgres.yaml
  - redis/redis.yaml
  - meilisearch/meilisearch.yaml
  - minio/minio.yaml
  - api/api.yaml
  - mail-worker/mail-worker.yaml
  - search-worker/search-worker.yaml
  - web/web.yaml
  - ingress/ingress.yaml
